# Generated by Django 2.0.4 on 2018-04-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180404_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
