# Generated by Django 2.0.4 on 2018-04-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_paciente', models.CharField(max_length=200)),
                ('tipo', models.TextField(max_length=200)),
                ('resumo_evento', models.TextField(max_length=22)),
                ('regitstro', models.DecimalField(decimal_places=999, max_digits=999)),
                ('sexo', models.CharField(max_length=1)),
                ('id_paciente', models.DecimalField(decimal_places=999, max_digits=999)),
                ('evento', models.DecimalField(decimal_places=999, max_digits=999)),
                ('gravidade', models.TextField()),
            ],
        ),
    ]
