# Generated by Django 2.0.4 on 2018-04-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='regitstro',
            new_name='registro',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evento',
            field=models.CharField(max_length=999),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_paciente',
            field=models.CharField(max_length=999),
        ),
    ]
