# Generated by Django 2.0.4 on 2018-04-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180405_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='registro',
            field=models.CharField(max_length=999),
        ),
    ]
